# FROM BASE ALGO
debug: False

# FROM BASE PYTORCH ALGO
lr: 1e-4

# FROM DF_BASE
x_shape: [2, 256, 256]
frame_stack: 1
data_mean: [0, 0]
data_std: [1, 1]
external_cond_dim: 4 #${dataset.action_dim}
external_conditions: ["rgb_video"]
context_frames: 0
# training hyperparameters

# diffusion-related
uncertainty_scale: 1
guidance_scale: 0.0
chunk_size: 1 # -1 for full trajectory diffusion, number to specify diffusion chunk size
scheduling_matrix: full_sequence
noise_level: random_all
causal: False

# FROM DF_FLOW
n_frames: 1
frame_skip: 1
metadata: "home/iyu/scene-jacobian-discovery/diff-force/diffusion_forcing/data/rod_flow/metadata.json"

# training hyperparameters
weight_decay: 2e-3
warmup_steps: 10000
optimizer_beta: [0.9, 0.99]

diffusion:
  # training
  beta_schedule: sigmoid
  objective: pred_x0
  use_fused_snr: True
  cum_snr_decay: 0.96
  clip_noise: 6.
  # sampling
  sampling_timesteps: 50 #100
  ddim_sampling_eta: 1.0
  stabilization_level: 15
  schedule_fn_kwargs: {}
  use_snr: False
  use_cum_snr: False
  snr_clip: 5.0
  timesteps: 1000
  # architecture
  architecture:
    network_size: 8 #16
    attn_heads: 4
    attn_dim_head: 32
    dim_mults: [1, 2, 4]
    resolution: 256
    attn_resolutions: [16, 32, 64]
    use_init_temporal_attn: True
    use_linear_attn: True
    time_emb_type: rotary

metrics:
  - fvd
  # - fid
  # - lpips
